//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace store
{
    using System;
    using System.Collections.Generic;
    
    public partial class Deal_product
    {
        public long id_deal_product { get; set; }
        public long deal { get; set; }
        public long product { get; set; }
    
        public virtual Deals Deals { get; set; }
        public virtual Products Products { get; set; }
    }
}
