//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace store
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class electronic_shopEntities : DbContext
    {
        public electronic_shopEntities()
            : base("name=electronic_shopEntities")
        {
        }


        private static electronic_shopEntities _context;

        public static electronic_shopEntities GetContext()
        {

            if (_context == null)
                _context = new electronic_shopEntities();
            return _context;

        }

        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Deal_product> Deal_product { get; set; }
        public virtual DbSet<Deals> Deals { get; set; }
        public virtual DbSet<Gender> Gender { get; set; }
        public virtual DbSet<Manufacturers> Manufacturers { get; set; }
        public virtual DbSet<Products> Products { get; set; }
        public virtual DbSet<Status_deal> Status_deal { get; set; }
        public virtual DbSet<Storage> Storage { get; set; }
        public virtual DbSet<sysdiagrams> sysdiagrams { get; set; }
        public virtual DbSet<Type_electronic> Type_electronic { get; set; }
        public virtual DbSet<Type_products> Type_products { get; set; }
        public virtual DbSet<User_type> User_type { get; set; }
        public virtual DbSet<Users> Users { get; set; }
    }
}
