//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace store
{
    using System;
    using System.Collections.Generic;
    
    public partial class Type_products
    {
        public long id_type_products { get; set; }
        public long product { get; set; }
        public long type { get; set; }
    
        public virtual Products Products { get; set; }
        public virtual Type_electronic Type_electronic { get; set; }
    }
}
